### ISSUE TITLE
install hydrotools fails with digest, glue

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/hydro-tools#222]
- Problem: install_github fails with digest ```Error: Failed to install 'hydrotools' from GitHub: (converted from warning) cannot remove prior installation of package 'digest' ``` saying it cannot remove existing package, but digest is *not* installed.
- Solution: install 'digest' and 'glue' separately, ````install.packages('glue')```

- But this is a bad solution!  See: https://github.com/r-lib/remotes/issues/403

**Comment by rburghol** [comment]
@SELoomis copied email here, as tis all seems related -- The R6 package is installed with version 2.5.0, and I'm running R version 4.0.0
![image](https://user-images.githubusercontent.com/4571170/111528923-f519ec80-8737-11eb-9e5e-bf0b76f42c23.png)

When it asks you to update 1,2 or 3, try just pressing enter.  Maybe it will work?  Also, for my knowledge, what version of R6 do you now have?

**Comment by SELoomis** [comment]
R6 is version 2.5.0, R is version 4.0.0.  I updated all (I think that's choice 1?) the first time I tried and it hasn't asked me again since that first time.

**Comment by rburghol** [comment]
How about trying this at the Rstudio command prompt beefore installing:
```
R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"
```

I am not sure if this is a *good* idea in general, but for this install_github it might be needed.  Now, I don't see that other packages require me to do this, so I am pinging @jdkleiner as he may have a better understanding of this than I.

**Comment by SELoomis** [comment]
Nope, didn't work :(  
If it is of any use, part of the error say that R6 was built under R 4.0.4, which is a newer version.  Everyone else has R 4.0.0 or earlier so I'm not sure why mine wouldn't work if theirs didn't for that reason, but thought it was worth mentioning!

**Comment by rburghol** [comment]
Sarah - been looking through this, looks like the best approach (for now) is to install packages one at a time?  I *think* their might be efficiencies gained by trying to identify which packages are installed by other packages in that same list?

**Comment by rburghol** [comment]
@SELoomis -- I have a new thing to try (a variation on a previous attempt). Run the following from the command lone:
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
```
