### ISSUE TITLE
om_vahydro_metric_grid  excludes features that don't have the first metric

### ISSUE THREAD

**Issue by BrendanBrogan** [HARPgroup/hydro-tools#426]
on_vahydro_metric_grid uses a for loop to go through rivdf, the runid and metrics it needs to pull. During the first loop through it creates the alldata df based on what it just pulled, a df called rawdata. Then, for each next loop it does a left join to add on the new column. 

The problem is that because its a left join, if a feature did not have the very first metric, it will not be included in the result (since it will only be in the RIGHT dataframe). This is why I was saying the river segments identified in the HARP summaries were "unmodelled", metric_grid did not pull a pid because it was missing the first metric.

Code that builds the combined data frame
`
        select a.*, b.attribute_value as ",
        runlabel, 
        "from alldata as a 
        left outer join rawdata as b 
        on (
          a.featureid = b.featureid
      `

To get around this, in each loop I made an exception clause where it looks for any rseg that was not included in the combined dataframe, Then, it pulls the relevant data, adds an NA for all other columns (since if it was excluded up to this point that means that it did not have any of the other metrics), messes with the formatting and rbinds it to the alldata result.
```
if (sum(!(rawdata$pid %in% alldata$pid)) > 0) {
    ## Add them back in 
    ## Pull out the features that are missing
    adddata <- rawdata[!(rawdata$pid %in% alldata$pid),]  

    ## Format to match alldata (This will only happen after at least 1 column has been added to alldata)
    adddata = sqldf(
      paste("select a.pid, a.propname, a.hydrocode, a.featureid, a.riverseg, a.attribute_value as ",
            runlabel, 
            "from adddata as a ")
    )
    ## Fill in any existing columns with NAs, since up to this point it has been
    adddata[,(ncol(adddata)+1):(ncol(alldata))] <- NA
    ## Rearrange the columns slightly
    adddata <- adddata[,c(1:5,7:ncol(alldata),6)]
    ##Make the names match for rbind
    names(adddata) <- names(alldata)

    alldata <- rbind(alldata,adddata)
}
```

This feels a little clunky, because I am manually moving the columns around. But it doesn't use any packages and works with the existing format. Once a feature has been added to the alldata df, it will not need to run this section again unless there are more excluded features in the next iteration.

Updates are on branch metric_grid_update

**Comment by rburghol** [comment]
Hey @BrendanBrogan - I agree this is a flaw, and actually attempted to fix this last month, and pushed an update that both Connor and I have tested.  IT essentially does what you wanted, but replaces the left outer join with a FULL join.

Code here: https://github.com/HARPgroup/hydro-tools/blob/cdc2730982b445b1e1379d712f62a5a9ea8c87df/R/om_vahydro_metric_grid.R#L92

Does this accomplish what you need?  If so, you should be able to reinstall hydrotools and it should worl.

**Comment by BrendanBrogan** [comment]
Oh yeah, that would do it. Alright, I will update my package. Thanks!
